apiVersion: v2
appVersion: "1.0"
description: A Helm chart for darts-gateway App
name: darts-gateway
home: https://github.com/hmcts/darts-gateway
version: 0.0.30
maintainers:
  - name: HMCTS darts team
dependencies:
  - name: java
    version: 5.0.4
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
